# Generated by Django 3.1.1 on 2020-10-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(verbose_name='경도')),
                ('y', models.FloatField(verbose_name='위도')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('sns', models.TextField(blank=True, verbose_name='SNS')),
                ('open_time', models.TextField(blank=True, verbose_name='운영시간')),
                ('Info', models.TextField(blank=True, verbose_name='카페이야기')),
                ('story', models.FileField(blank=True, upload_to='store/story', verbose_name='스토리')),
                ('icon', models.ImageField(blank=True, upload_to='store/icon', verbose_name='아이콘')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '카페',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '태그들',
            },
        ),
        migrations.CreateModel(
            name='StorePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
            options={
                'verbose_name_plural': '사진',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
            options={
                'verbose_name_plural': '리뷰',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.store')),
            ],
            options={
                'verbose_name_plural': '메뉴',
            },
        ),
    ]
