# Generated by Django 3.1.1 on 2020-10-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='대표이미지'),
        ),
    ]
