# Generated by Django 3.0.6 on 2020-10-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카페이름')),
                ('x', models.FloatField(verbose_name='경도')),
                ('y', models.FloatField(verbose_name='위도')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='카페사진')),
            ],
        ),
    ]
